# 邮件参数配置
mail-config:
  smtp_server: smtp.126.com
  smtp_port: "25"
  username: your@email.com
  password: your_password_or_auth_code
  from: your@email.com
  to: recipient1@email.com,recipient2@email.com
  send_mode: 1  # 1-单个发送，3-群发

# IPv4地址API列表
ip-v4-list:
  - https://ipinfo.io/ip
  - https://api.ipify.org
  - https://checkip.amazonaws.com

# IPv6地址API列表
ip-v6-list:
  - https://api6.ipify.org?format=json
  - https://v6.ident.me/
  - https://ipv6.icanhazip.com/

# 任务参数配置
task-para:
  cron_expression: "*/1 * * * *"  # 每分钟检查一次
